language: node_js
node_js:
- '8.6.0'
before_script:
- node --version
- npm --version
script:
- npm run test
after_success:
- CODECLIMATE_REPO_TOKEN=$CODECLIMATE_TOKEN codeclimate-test-reporter < coverage/lcov.info
- npm run coverage
