language: node_js
node_js:
- '8'
script:
- npm run test
after_success:
- travis_wait CODECLIMATE_REPO_TOKEN=$CODECLIMATE_TOKEN codeclimate-test-reporter < coverage/lcov.info
- travis_wait npm run coverage
