language: node_js
node_js:
  - node
before_script:  
 - npm install -g codeclimate-test-reporter 
 - npm run initialize:db
script:  
 - npm run test 
after_success:  
 - CODECLIMATE_REPO_TOKEN=CODECLIMATE_TOKEN codeclimate-test-reporter < coverage/lcov.info